remote_theme: coursweb/jk-theme
title: Fontes typo IMD
description: Fontes typographiques IMD
lang: fr-FR
markdown: GFM
chapters:
# - title: Infos IMD
#   url: https://code.eracom-pedagogique.ch/infos-profs-imd/
# - title: Pédagogie
#   url: https://code.eracom-pedagogique.ch/pedagogie/
 - title: Fontes IMD
   url: https://code.eracom-pedagogique.ch/fontes-imd/
footer_col_1: <ul class="contact-list">
  <li>Eracom, Lausanne</li>
  <li>2021</li></ul>
footer_col_2: <ul class="social-media-list"><li><a href="https://github.com/eracom/fontes-imd">Lien Github</a></li></ul>
footer_col_3: Fontes typographiques IMD.